# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{viewcumber}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["gregbell", "pcreux", "samuelreh"]
  s.date = %q{2010-11-10}
  s.default_executable = %q{viewcumber}
  s.executables = ["viewcumber"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/viewcumber",
     "lib/assets/jquery-min.js",
     "lib/assets/viewcumber.css",
     "lib/assets/viewcumber.js",
     "lib/assets/viewless.html",
     "lib/viewcumber.rb",
     "test/helper.rb",
     "test/test_viewcumber.rb",
     "viewcumber.gemspec"
  ]
  s.homepage = %q{http://github.com/versapay/viewcumber}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Cucumber formatter for easily viewing each step of your scenarios}
  s.test_files = [
    "test/helper.rb",
     "test/test_viewcumber.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cucumber>, [">= 0.8.5"])
      s.add_runtime_dependency(%q<capybara>, [">= 0.3"])
    else
      s.add_dependency(%q<cucumber>, [">= 0.8.5"])
      s.add_dependency(%q<capybara>, [">= 0.3"])
    end
  else
    s.add_dependency(%q<cucumber>, [">= 0.8.5"])
    s.add_dependency(%q<capybara>, [">= 0.3"])
  end
end

